# Generated by Django 5.2.4 on 2025-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
