# Generated by Django 5.2.4 on 2025-07-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_horoscope_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
