# Generated by Django 5.2.4 on 2025-08-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_alter_horoscope_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('otziv', models.TextField()),
            ],
        ),
    ]
